### PR TITLE
fix undefined on fetchThingMetadata

### LINKED ISSUE #61: TypeError: Cannot read property '0' of undefined
https://github.com/Mintbase/mintbase-js/blob/4a5906fde6d692b35fa120f6d7e6586e8267742d/src/api.ts#L143

Should be `result.thing.tokens[0]`

### PR DESCRIPTION
**Pull request by jpcloureiro**
fixes #61

### CODE REVIEW

File: src/api.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export class API {
     if (result.thing.length === 0)
       return formatResponse({ error: `${thingId} is not a valid thing.` })
 
-    const thing = result.token[0]
+    const thing = result.thing.token[0]
```
Comment (microchipgnu) [inline src/api.ts:143]: I think it is `result.thing.tokens[0]`

**Review by microchipgnu — CHANGES_REQUESTED** [review]

File: src/types.ts [hunk 2]
```diff
@@ -182,6 +182,30 @@ interface MintMetadata {
...
+  split_revenue: null
+  tags: string[]
+  media: string
+  extra: []
+  title: string
+  store: string
+  external_url: string
+  type: string
+}
+
```
Comment (microchipgnu) [inline src/types.ts:208]: Why not reuse `MetadataField`?

**Review by microchipgnu — CHANGES_REQUESTED** [review]

File: src/types.ts (hunk 2 above)
Comment (jpcloureiro) [reply src/types.ts]: 👀

**Review by microchipgnu — APPROVED** [review]
